### ISSUE TITLE
k8s: Use of `reduce_dict()` makes it impossible to delete parts of manifests

### ISSUE THREAD

**Issue by vain** [bundlewrap/bundlewrap#402]
`items/kubernetes.py` has this:

```
    def sdict(self):
        ...
            return {'manifest': json.dumps(reduce_dict(
                full_json_response,
                json.loads(self.manifest),
            ), indent=4, sort_keys=True)}
```
IIUC, this means you can never remove parts of already deployed manifests.

Let's assume `full_json_response` is this:

```
'foo': {
    'bar': 123,
    'baz': 456
}
```

And `self.manifest` is this:

```
'foo': {
    'bar': 123
}
```

Then `reduce_dict()` will only return this:

```
'foo': {
    'bar': 123
}
```

This makes `sdict()` return exactly the same value as `self.manifest`, which means bw won't detect a change.

The expected result is: bw deploys a new version of the item to effectively remove the `baz` key.

I guess the purpose of `reduce_dict()` is to filter noise? If we were to remove the call to `reduce_dict()`, no item would ever be OK?

**Comment by trehn** [comment]
I‘m not sure you *can* remove the extra key. How would you do that with plain kubectl?

The JSON we get back from the API is an indistinguishable hodgepodge of auto-generated metadata, default values and things we actually set ourselves. It‘s pretty much impossible to filter these things without super-deep knowledge of the k8s API and every resource type therein. Thus, we only enforce what the user actually puts in items.py. This matches the behavior of most other items.

You can‘t say „this key should be set to the default k8s provides“. If you care, you must set the key explicitly.

I cannot see how else we could do this.

**Comment by vain** [comment]
Plain kubectl can do it.

Basis for our test:

```
$ kubectl -n bw-debug get -o json po
{
                "containers": [
                    {
                        "command": [
                            "/bin/sleep",
                            "1d"
                        ],
                        "image": "debian:latest",
                        "imagePullPolicy": "Always",
                        "name": "bw-debug",
                        "resources": {},
                        "terminationMessagePath": "/dev/termination-log",
                        "terminationMessagePolicy": "File",
                        "volumeMounts": [
                            {
                                "mountPath": "/var/run/secrets/kubernetes.io/serviceaccount",
                                "name": "default-token-tkk5k",
                                "readOnly": true
                            }
                        ]
                    }
                ],
}
```

Reconfigure, add `env` by pushing some yaml, which looks like this:

```
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: bw-debug
spec:
  replicas: 1
  selector:
    matchLabels:
      app: bw-debug
  template:
    metadata:
      labels:
        app: bw-debug
    spec:
      containers:
      - command:
        - /bin/sleep
        - 1d
        image: debian:latest
        name: bw-debug
        env:
        - name: foo
          value: bar
```

```
$ kubectl -n bw-debug apply -f - </tmp/test.yaml
deployment.extensions "bw-debug" configured
$ kubectl -n bw-debug get -o json po
{
                "containers": [
                    {
                        "command": [
                            "/bin/sleep",
                            "1d"
                        ],
                        "env": [
                            {
                                "name": "foo",
                                "value": "bar"
                            }
                        ],
                        "image": "debian:latest",
                        "imagePullPolicy": "Always",
                        "name": "bw-debug",
                        "resources": {},
                        "terminationMessagePath": "/dev/termination-log",
                        "terminationMessagePolicy": "File",
                        "volumeMounts": [
                            {
                                "mountPath": "/var/run/secrets/kubernetes.io/serviceaccount",
                                "name": "default-token-tkk5k",
                                "readOnly": true
                            }
                        ]
                    }
                ],
}
```

Then push another yaml without the `env`:

```
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: bw-debug
spec:
  replicas: 1
  selector:
    matchLabels:
      app: bw-debug
  template:
    metadata:
      labels:
        app: bw-debug
    spec:
      containers:
      - command:
        - /bin/sleep
        - 1d
        image: debian:latest
        name: bw-debug
```

```
$ kubectl -n bw-debug apply -f - </tmp/test.yaml
deployment.extensions "bw-debug" configured
$ kubectl -n bw-debug get -o json po
{
                "containers": [
                    {
                        "command": [
                            "/bin/sleep",
                            "1d"
                        ],
                        "image": "debian:latest",
                        "imagePullPolicy": "Always",
                        "name": "bw-debug",
                        "resources": {},
                        "terminationMessagePath": "/dev/termination-log",
                        "terminationMessagePolicy": "File",
                        "volumeMounts": [
                            {
                                "mountPath": "/var/run/secrets/kubernetes.io/serviceaccount",
                                "name": "default-token-tkk5k",
                                "readOnly": true
                            }
                        ]
                    }
                ],
}
```

If you try to do the same via bw, bw tells you that everything is fine after you removed the `env` and that no changes are needed. That's wrong or, at the very least, pretty misleading. :|

Phew. That's a hard one.
